title:              JUN BLOG
email:              cwj0852@gmail.com
description:        study diary
author:             C.W.J
baseurl:            ""
url:                "https://cwj0321.github.io"

# Social Profiles
twitter_username:   NULL
github_username:    cwj0321
facebook_username: NULL
instagram_username: woongjun_choi 
linkedin_username: NULL

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

